### ISSUE TITLE
Send just the diff

### ISSUE THREAD

**Issue by zenorocha** [laurilehmijoki/jekyll-s3#1]
Now, when you hit `jekyll-s3`, all files are transfered to Amazon.
But it will be nice if you send just the new files and not all of them.

**Comment by laurilehmijoki** [comment]
Hi Zenorocha. You are right. It's unnecessary to push the whole site every time.

I've been thinking of creating a Ruby lib for diffing between the local files and S3 files. Jekyll-s3 could then use that lib to identify the files to be sent.

I haven't had the time to work on it though. 

All help is welcome.

**Comment by laurilehmijoki** [comment]
The code for sending just the diff is ready in master. I'll release it within a few days. If you want to, you can help in testing it. More info here: https://github.com/laurilehmijoki/jekyll-s3/wiki/How-to-test-an-unreleased-version-of-jekyll-s3.

**Comment by zenorocha** [comment]
Cool!

**Comment by laurilehmijoki** [comment]
Jekyll-s3 v. 0.0.6 is now out. It will only send the new or changed files.

Happy blogging!
