### ISSUE TITLE
Content-Type is not being set correctly on uploaded files

### ISSUE THREAD

**Issue by matthodan** [laurilehmijoki/jekyll-s3#11]
When I run `jekyll-s3` for the first time with a fresh bucket name everything appears to work smoothly, but when I try to visit the site via the link provided by the output I get a 403 forbidden error.

These are the issues I've noticed:
- New S3 bucket is not automatically configured as a website.  In fact, the URL returned is not for a website, but rather accessing the files directly.  This means that "http://www.example.com/index.html" will work, but "http://www.example.com/" will not.
- Neither a bucket policy nor individual file permissions have been set to allow "Everyone" to "Open/Download" the uploaded files.
- The "Content-Type" metadata has been set to "image/[jpeg/png]" for every file, even the html, xml, js and css files.

Am I the only one with these issues?

**Comment by matthodan** [comment]
I just tried deploying a site using v0.0.5 and had a much better experience.  The content-type header and permissions were correctly assigned automatically.  All I had to do was enable website hosting in the AWS S3 management console.

**Comment by laurilehmijoki** [comment]
I just released the version 2.0.0. In that version, `jekyll-s3` adds the content-type info into the uploaded files.

The content-type problem appeared when I changed the gem _aws-s3_ into _aws-sdk_. This happened in v.0.0.6. That's why the version 0.0.5 sets the content-type correctly. To recap, this problem has been solved in v.2.0.0.

Happy blogging
Lauri

**Comment by laurilehmijoki** [comment]
About the automatically configuring the S3 bucket as a website: this feature is not yet in Jekyll-s3. I've created a new issue on it: https://github.com/laurilehmijoki/jekyll-s3/issues/12.

**Comment by matthodan** [comment]
Thanks!
