### ISSUE TITLE
Sync vs push everything

### ISSUE THREAD

**Issue by miloshadzic** [laurilehmijoki/jekyll-s3#13]
Is there a way to just sync what's different from the s3 bucket? If you have a lot of media, `jekyll-s3` takes a long time to publish changes.

**Comment by laurilehmijoki** [comment]
The answer to your question is yes. Jekyll-s3 synchronises only the difference between your local Jekyll site and the S3 bucket.

Which version are you using? The synchronisation feature appeared in the version 0.0.6.

**Comment by miloshadzic** [comment]
Thanks, it works now. It seems I've been using an ancient version :/
