### ISSUE TITLE
"US Standard" is the only supported S3 endpoint

### ISSUE THREAD

**Issue by BewhiskeredBard** [laurilehmijoki/jekyll-s3#17]
This is a fairly limiting issue that would be trivial to fix. I'll try to come up with a patch.

**Comment by laurilehmijoki** [comment]
Hello Jordan

It's a good idea to allow usage of endpoints other than the US Standard.

Please note that you need to modify also the gem [configure-s3-website](https://github.com/laurilehmijoki/configure-s3-website/). Currently it uses only the US Standard endpoint.

Please accompany the patches with proper tests.

**Comment by laurilehmijoki** [comment]
I added documentation on how to contribute: https://github.com/laurilehmijoki/jekyll-s3#development.

If you think that there's something missing in that documentation, please let me know.

**Comment by laurilehmijoki** [comment]
Hello

The version 2.3.0 now contains support for non-standard AWS regions. See README for more info.
