### ISSUE TITLE
Unchanged files are reuploaded anyway

### ISSUE THREAD

**Issue by dguido** [laurilehmijoki/jekyll-s3#19]
After the change from #18, files with erroneous MD5 hashes (they always have a "-5" added to the end) are reuploaded on every sync.

**Comment by laurilehmijoki** [comment]
Do you know why they have this "-5" at the end?

Have you set the MD5 checksum yourself, or have you let S3 do the calculation for you?

**Comment by dguido** [comment]
I have not modified filey-diff or jekyll-s3. I just installed both with gem install and let it run. The only modifications I made to either library was to support printing out status updates on each file to investigate issue #18.

I should also note that the same two files always have the extra "-5" on them.

**Comment by dguido** [comment]
As an experiment, I deleted the two misbehaving files and sync'd the website, thus deleting them on S3. I put the files back in my _site directory and sync'd to upload them back. Then sync'd a third time to see if jekyll-s3 would think they changed. jekyll-s3 thought they changed and overwrote the files on the server unnecessarily.

I don't know what to do to track down this bug. We probably should find the root cause for these misreported MD5s. Do you have any suggestions or debugging output I should add to the affected libraries that would help?

**Comment by laurilehmijoki** [comment]
Hi Dan

The gem _filey-diff_ retrieves the MD5s like this:
- S3 objects: https://github.com/laurilehmijoki/filey-diff/blob/master/lib/filey-diff/data-sources/aws_sdk_s3.rb#L23
- Local file system object: https://github.com/laurilehmijoki/filey-diff/blob/master/lib/filey-diff/data-sources/file_system.rb#L19

If you are able to find a problem in the code logic above, please let me know.

**Comment by laurilehmijoki** [comment]
Dan, try the version 1.0.2 of _filey-diff_. This problem should be fixed there. See https://github.com/laurilehmijoki/filey-diff/pull/2 for more details.

`gem update filey-diff` should do the job.

Please re-open this issue if the problem persists.

**Comment by dguido** [comment]
We're closer to the root cause but postmodern's pull request doesn't fix the issue: the same two files are re-uploaded on every run of jekyll-s3. It looks like the [forum link](https://forums.aws.amazon.com/thread.jspa?messageID=203510#203510) from that pull request includes more information that filey-diff may need to consider.
