### ISSUE TITLE
Add ability to define redirects

### ISSUE THREAD

**Issue by BewhiskeredBard** [laurilehmijoki/jekyll-s3#21]
S3 allows creating HTTP redirects (see http://docs.amazonwebservices.com/AmazonS3/latest/dev/how-to-page-redirect.html).

I could see doing something like adding a set of redirects in _jekyll_s3.yml and having jekyll-s3 set them when executed. For example:

```
s3_id: myid
s3_secret: mysecret
s3_bucket: mybucket
s3_redirects:
  "/post/1230981/old-tumblr-post-url": "/posts/2012/02/new-jekyll-post-url"
  "/rss": "/posts/rss"
```

If this is a feature the maintainers and others would like to see, I would be happy to implement it.

**Comment by laurilehmijoki** [comment]
Adding support for S3 redirects is a supercool idea!

**Comment by AlexanderEkdahl** [comment]
You can add redirects to Jekyll using [this](http://www.marran.com/tech/creating-redirects-with-jekyll/) technique.

However, letting this gem hande the redirects would probably make more sense and be a lot faster.

+1

**Comment by jakenet** [comment]
+1 for me as well.  this is exactly what I need.

**Comment by laurilehmijoki** [comment]
As of version 2.6.0, `jekyll-s3` supports defining redirects in the `_jekyll_s3.yml` file.

For more info, see https://github.com/laurilehmijoki/jekyll-s3#configuring-redirects-on-your-jekyll-s3-website
