### ISSUE TITLE
Add option to gzip files prior to upload

### ISSUE THREAD

**Issue by BewhiskeredBard** [laurilehmijoki/jekyll-s3#24]
The only way to server gzip'd files from S3 and CloudFront is to upload them that way. It would be nice if there was an option to define which file extensions to gzip, and have jekyll-s3 take care of it.

```
gzip_extensions: [html, js, css, svg, txt]
```

**Comment by laurilehmijoki** [comment]
Implemented in #27.

**Comment by laurilehmijoki** [comment]
Released in version 2.4.0.
