### ISSUE TITLE
jekyll-s3 does not use options from Jekyll _config.yml

### ISSUE THREAD

**Issue by juev** [laurilehmijoki/jekyll-s3#3]
I'm use this options in my `_config.yml`:

```
source:      source
destination: public
plugins:     plugins
```

and when I run `jekyll-s3` command I get an error message:

```
I can't find any directory called _site. Are you in the right directory?
```

Why?

**Comment by laurilehmijoki** [comment]
At the moment jekyll-s3 only supports the default source and destination directories of Jekyll.

I welcome pull requests that fix this shortcoming.
