### ISSUE TITLE
`initialize': not in gzip format (Zlib::GzipFile::Error) when running jekyll-s3 on Mt Lion.

### ISSUE THREAD

**Issue by MikeWills** [laurilehmijoki/jekyll-s3#32]
I get the following error:

> $ jekyll-s3
> Deploying _site/\* to xxx.com
> /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:41:in `initialize': not in gzip format (Zlib::GzipFile::Error)
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:41:in`open'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:41:in `last_modified_and_md5_from_gzipped'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:22:in`block in do_internal_load'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/core/collection.rb:50:in `each'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/core/collection.rb:50:in`block in each'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/core/collection/with_limit_and_next_token.rb:61:in `_each_batch'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/core/collection.rb:82:in`each_batch'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/core/collection.rb:49:in `each'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/aws-sdk-1.8.5/lib/aws/s3/object_collection.rb:282:in`each'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:11:in `map'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/aws_sdk_s3.rb:11:in`do_internal_load'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/data-sources/data_source.rb:8:in `get_fileys'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/comparison.rb:28:in`select_in_outer_array'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/filey-diff-1.1.0/lib/filey-diff/comparison.rb:11:in `list_changed'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/lib/jekyll-s3/diff_helper.rb:8:in`resolve_files_to_upload'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/lib/jekyll-s3/uploader.rb:34:in `upload_files'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/lib/jekyll-s3/uploader.rb:11:in`run'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/lib/jekyll-s3/cli.rb:14:in `run'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/lib/jekyll-s3/cli.rb:7:in`run'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/gems/jekyll-s3-2.4.2/bin/jekyll-s3:7:in `<top (required)>'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/bin/jekyll-s3:23:in`load'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/bin/jekyll-s3:23:in `<main>'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
>     from /Users/username/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'

I was able to run this once, but not since then. All that has changed is the site as I was developing it.

**Comment by MikeWills** [comment]
never mind same issue as #30.

**Comment by laurilehmijoki** [comment]
I also got this error after installing Ruby 2.0.0.

I was not able to get around the problem by following the steps in #30. I have not yet figured out the root cause. Have you?

When I switched back to Ruby 1.9.3, the error did not occur.

**Comment by jeremi** [comment]
the solution in #30 worked for me.

**Comment by MikeWills** [comment]
I guess technically it's a work-around not a solution... but I didn't know if that was designed as intended or not since I am new to the project.

**Comment by jeremi** [comment]
yes, right, it work the first time, but break again after an update.
In the meantime, I disabled the verification of the file, and re-upload everything.

**Comment by sondr3** [comment]
Just chiming in to say that I'm also getting this error, but I'm not getting the workaround to work for me. I get the error even though I've emptied the _site.

**Comment by bkaid** [comment]
I'm also getting this issue where jekyll-s3 will work once with gzip enabled on a clean s3 bucket but then fails every other time unless the bucket is emptied out first.  I tried updating to the latest aws-sdk but that didn't help.  I also ensured jekyll-s3 is using the lastest filey-diff gem which recently added gzip support.

**Comment by joejoejoew** [comment]
This is not working for me either with ruby-2.0.0-p195.  With ruby-1.9.3-p429, everything works fine.

**Comment by nicolashery** [comment]
Yes same here, error with Ruby 2.0.0, works fine with Ruby 1.9.3.

**Comment by laurilehmijoki** [comment]
The problem seems to be that in Ruby 2.0.0 `Net::HTTP` automatically decompresses gzip'ed HTTP responses. 

http://ruby-doc.org/stdlib-2.0/libdoc/net/http/rdoc/Net/HTTP.html#label-Compression

**Comment by laurilehmijoki** [comment]
Try updating the [filey-diff](https://github.com/laurilehmijoki/filey-diff) gem to version `1.1.2`. It should solve the problem. The fix commit is [here](https://github.com/laurilehmijoki/filey-diff/commit/afe4f9dbdeae93c91a58bba7632119cf8c521c53). Please get back to me if you spot any problems in the solution.

To summarise: I was able to use gzip with Ruby 2.0.0, when I upgraded the `filey-diff` gem to version `1.1.2`.

**Comment by bdesham** [comment]
Updating filey-diff to 1.1.2 made everything work for me. Thanks!
