### ISSUE TITLE
Ping services on update

### ISSUE THREAD

**Issue by pathawks** [laurilehmijoki/jekyll-s3#38]
Could there be a way to ping a PubSubHubbub hub (or another online service, like Feedburner) after a site has been successfully uploaded to S3?

**Comment by adelevie** [comment]
Maybe have a config option for a callback URL. Jekyll-s3 would then POST to it after each build with a given payload. Though I don't see why this would need to exist in this library.

**Comment by pathawks** [comment]
A config option for a callback URL sounds like it could work well.

**Comment by adelevie** [comment]
Just wondering what your thoughts are as to why this should be a concern of this gem? Not saying it shouldn't be, but I'm curious what you might think.

**Comment by pathawks** [comment]
Perhaps it shouldn't be, it just seems like the most natural step in my workflow.
`jekyll-s3` knows if my feed has been updated, will invalidate the file in Cloudfront, and try to let interested services know that there is a new version available.

**Comment by pathawks** [comment]
Perhaps a simple Rake file would be better suited for the job?

**Comment by laurilehmijoki** [comment]
`jekyll-s3` is for uploading files to S3 and doing S3 website stuff. Interacting with non-S3 systems is perhaps better handled elsewhere.

For example, you can create a Bash or Ruby script that first calls `jekyll-s3` and then pings your services.
