### ISSUE TITLE
unreleased version of jekyll-s3 errors

### ISSUE THREAD

**Issue by fhuel** [laurilehmijoki/jekyll-s3#4]
Hi Lauri, 
when I try to run the unreleased version of jekyll-s3 I get this errors:

```
/Users/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- erubis (LoadError)
    from /Users/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /tmp/jekyll-s3-testing/lib/jekyll-s3.rb:3:in `<top (required)>'
    from /Users/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/user/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /tmp/jekyll-s3-testing/bin/jekyll-s3:3:in `<main>'
```

I'm not sure if it could be an issue with ruby versions or something due to dependancies ... anyway hope it can help

**Comment by laurilehmijoki** [comment]
I forgot to include the `bundle install` command in the wiki page. It should work if you now follow the updated instructions in https://github.com/laurilehmijoki/jekyll-s3/wiki/How-to-test-an-unreleased-version-of-jekyll-s3.

My bad!

**Comment by fhuel** [comment]
It seems to work great now, thank you
