### ISSUE TITLE
I need some help with serving static assets from CloudFront

### ISSUE THREAD

**Issue by sondr3** [laurilehmijoki/jekyll-s3#46]
I'm still very much a newbie with this so please bear with me. I've just configured and uploaded my Jekyll sites to S3, configured the CloudFront distributions and such, however my site is still using the S3 CSS/javascript files instead of those on CloudFront, is there anything configuration that I'm missing?

I'm my default.html for Jekyll I'm serving my CSS via {% stylesheets style %}. Thanks in advance.

**Comment by laurilehmijoki** [comment]
Hello

Your issue does not seem to be related to `jekyll-s3`. Instead, it might have something to do with the way you compile your site with `jekyll`. Take a look at the HTML file. Where does the CSS URL reference point to?
