### ISSUE TITLE
jekyll-3s testing error

### ISSUE THREAD

**Issue by antagomir** [laurilehmijoki/jekyll-s3#5]
I get the following when running jekyll-s3:

me@ubuntu:~/my.jekyll.site$ /tmp/jekyll-s3-testing/bin/jekyll-s3 
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- erubis (LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /tmp/jekyll-s3-testing/bin/../lib/jekyll-s3.rb:3
    from /tmp/jekyll-s3-testing/bin/jekyll-s3:3:in `require'
    from /tmp/jekyll-s3-testing/bin/jekyll-s3:3

**Comment by laurilehmijoki** [comment]
I forgot to include the `bundle install` command in the wiki page. It should work if you now follow the updated instructions in https://github.com/laurilehmijoki/jekyll-s3/wiki/How-to-test-an-unreleased-version-of-jekyll-s3.

My bad!
