### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by Jonovono** [laurilehmijoki/jekyll-s3#50]
I created a bucket www.howlett.io with region northern california.

In the config I have it:

s3_bucket: www.howlett.io

And I get the error

/Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/lib/configure-s3-website/http_helper.rb:54:in `call_api': AWS API call failed: (GenericError)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><RequestId>749CC81815093B65</RequestId><Bucket>www.howlett.io</Bucket><HostId>PRtzi0y8KyC9j2eZ7/Xs2RFmSi3+D14p3Y5CMZZi4FXhyAuZ+w8e06cX3xLUAIAO</HostId><Endpoint>www.howlett.io.s3.amazonaws.com</Endpoint></Error>
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/lib/configure-s3-website/http_helper.rb:7:in`call_s3_api'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/lib/configure-s3-website/s3_client.rb:34:in `enable_website_configuration'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/lib/configure-s3-website/s3_client.rb:12:in`configure_website'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/lib/configure-s3-website/runner.rb:4:in `run'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/gems/configure-s3-website-1.4.0/bin/configure-s3-website:12:in`<top (required)>'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/bin/configure-s3-website:19:in `load'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/bin/configure-s3-website:19:in`<main>'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/Jordan/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by laurilehmijoki** [comment]
Try adding the following line into `_jekyll_s3.yml`:

```
s3_endpoint: us-west-1
```

If your bucket resides in somewhere else than the [US Standard location](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region), you need to specify the `s3_endpoint` in the config file.

**Comment by laurilehmijoki** [comment]
I'm closing this issue as "will not fix". Please reopen if the problem persists.
