### ISSUE TITLE
new error after adding bundle install 

### ISSUE THREAD

**Issue by antagomir** [laurilehmijoki/jekyll-s3#6]
me@ubuntu:~/myjekyllsite$ /tmp/jekyll-s3-testing/bin/jekyll-s3
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- erubis (LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /tmp/jekyll-s3-testing/bin/../lib/jekyll-s3.rb:3
    from /tmp/jekyll-s3-testing/bin/jekyll-s3:3:in `require'
    from /tmp/jekyll-s3-testing/bin/jekyll-s3:3

**Comment by laurilehmijoki** [comment]
For some reason RubyGems cannot locate Erubis, a gem.

Do you have bundler installed? The command `which bundle` will tell.

If `bundle install` ran without errors for you, I'm out of ideas what could cause the problem.

I tried the [test](https://github.com/laurilehmijoki/jekyll-s3/wiki/How-to-test-an-unreleased-version-of-jekyll-s3) sequence on my 10.04 Ubuntu virtual machine, and there I was able to run the pre-released version of jekyll-s3. I installed Ruby by running `apt get install ruby ruby-dev rubygems libruby1.8-extras` (a rather long list of packages!).

Ruby 1.8 is quite old. If you use Ruby programs often, it might be a good idea to install Ruby 1.9 via [RVM](https://rvm.io/rvm/install/).

**Comment by laurilehmijoki** [comment]
I'm closing this issue now. Thanks for helping in testing, Antagomir!
