### ISSUE TITLE
Not recognizing changes until I run jekyll

### ISSUE THREAD

**Issue by allspiritseve** [laurilehmijoki/jekyll-s3#7]
I just updated to latest master, changed my layout file (which should change all pages) and ran jekyll-s3.  It didn't recognize any changes, but when I ran jekyll first, it did.  I also checked by editing a post to make sure it wasn't just layout changes it didn't recognize.

**Comment by laurilehmijoki** [comment]
`jekyll-s3` does not run `jekyll`. As a consequence, your changes were not picked up by `jekyll-s3`.

To recap: before running `jekyll-s3`, you need to run `jekyll`. Otherwise your changes will not be recognised by `jekyll-s3`. Jekyll-s3 has worked this way from the beginning.

**Comment by allspiritseve** [comment]
Ah, ok. I thought I remembered it doing so in the past... oh well.
